export const ORDER_SEQUENCE = [
  'ORDER_PLACED',
  'STORE_ACCEPTED',
  'PREPARING_GIFT',
  'READY_FOR_PICKUP',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
] as const;

export const DELIVERY_FEES: Record<string, number> = {
  STANDARD: 49,
  EXPRESS: 99,
  SCHEDULED: 79,
};

export const STORE_NEXT: Record<string, string[]> = {
  ORDER_PLACED: ['STORE_ACCEPTED', 'REJECTED'],
  STORE_ACCEPTED: ['PREPARING_GIFT'],
  PREPARING_GIFT: ['READY_FOR_PICKUP'],
  READY_FOR_PICKUP: ['OUT_FOR_DELIVERY'],
  OUT_FOR_DELIVERY: ['DELIVERED'],
  DELIVERED: [],
  REJECTED: [],
};
